# Generated by Django 6.0.2 on 2026-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payrolls/'),
        ),
    ]
