# Generated by Django 6.0.2 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_payment',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave')], max_length=10),
        ),
    ]
