# Generated by Django 6.0.2 on 2026-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leave_leave_payment_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='leave_balance',
            field=models.IntegerField(default=12),
        ),
    ]
